/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calcoloaree;

/**
 *
 * @author Sebastiano
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    
    Grafico g;
    
    int tipoArea;
    
    public Finestra() {
        initComponents();
        
        g=new Grafico(cGrafico.getWidth(), cGrafico.getHeight());
        cGrafico.add(g);
        
        tipoArea=3;
        
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cGrafico = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        risTxt = new javax.swing.JTextArea();
        areacRb = new javax.swing.JRadioButton();
        codeRb = new javax.swing.JRadioButton();
        codaSxRb = new javax.swing.JRadioButton();
        codaDxRb = new javax.swing.JRadioButton();
        sxT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dxT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        baseT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout cGraficoLayout = new javax.swing.GroupLayout(cGrafico);
        cGrafico.setLayout(cGraficoLayout);
        cGraficoLayout.setHorizontalGroup(
            cGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cGraficoLayout.setVerticalGroup(
            cGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Calcola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Risultato:");

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        risTxt.setBackground(new java.awt.Color(0, 51, 102));
        risTxt.setColumns(20);
        risTxt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        risTxt.setForeground(new java.awt.Color(204, 255, 255));
        risTxt.setRows(5);
        risTxt.setToolTipText("");
        risTxt.setDisabledTextColor(new java.awt.Color(204, 255, 255));
        risTxt.setEnabled(false);
        jScrollPane1.setViewportView(risTxt);

        areacRb.setBackground(new java.awt.Color(0, 51, 102));
        areacRb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        areacRb.setForeground(new java.awt.Color(255, 255, 255));
        areacRb.setText("Area Compresa");
        areacRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areacRbActionPerformed(evt);
            }
        });

        codeRb.setBackground(new java.awt.Color(0, 51, 102));
        codeRb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codeRb.setForeground(new java.awt.Color(255, 255, 255));
        codeRb.setSelected(true);
        codeRb.setText("Due Code");
        codeRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeRbActionPerformed(evt);
            }
        });

        codaSxRb.setBackground(new java.awt.Color(0, 51, 102));
        codaSxRb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codaSxRb.setForeground(new java.awt.Color(255, 255, 255));
        codaSxRb.setText("Una Coda (sinistra)");
        codaSxRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codaSxRbActionPerformed(evt);
            }
        });

        codaDxRb.setBackground(new java.awt.Color(0, 51, 102));
        codaDxRb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codaDxRb.setForeground(new java.awt.Color(255, 255, 255));
        codaDxRb.setText("Una Coda (destra)");
        codaDxRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codaDxRbActionPerformed(evt);
            }
        });

        sxT.setText("-2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Estremo Sinistro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Estremo Destro");

        dxT.setText("2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Base dei Rettangoli");

        baseT.setText("0.05");
        baseT.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sxT)
                    .addComponent(dxT)
                    .addComponent(baseT)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(areacRb)
                                .addComponent(codeRb)
                                .addComponent(codaSxRb)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(codaDxRb)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                    .addComponent(cGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baseT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(codaDxRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codaSxRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codeRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areacRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codaDxRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codaDxRbActionPerformed
        tipoArea=1;
        dxT.setEnabled(false);
        sxT.setEnabled(true);
        codaSxRb.setSelected(false);
        codeRb.setSelected(false);
        areacRb.setSelected(false);
    }//GEN-LAST:event_codaDxRbActionPerformed

    private void codaSxRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codaSxRbActionPerformed
        tipoArea=2;
        dxT.setEnabled(true);
        sxT.setEnabled(false);
        codaDxRb.setSelected(false);
        codeRb.setSelected(false);
        areacRb.setSelected(false);
    }//GEN-LAST:event_codaSxRbActionPerformed

    private void codeRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeRbActionPerformed
        tipoArea=3;
        dxT.setEnabled(true);
        sxT.setEnabled(true);
        codaDxRb.setSelected(false);
        codaSxRb.setSelected(false);
        areacRb.setSelected(false);
    }//GEN-LAST:event_codeRbActionPerformed

    private void areacRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areacRbActionPerformed
        tipoArea=4;
        dxT.setEnabled(true);
        sxT.setEnabled(true);
        codaDxRb.setSelected(false);
        codaSxRb.setSelected(false);
        codeRb.setSelected(false);
    }//GEN-LAST:event_areacRbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        g.setSx(Double.parseDouble(sxT.getText()));
        g.setDx(Double.parseDouble(dxT.getText()));
        g.setBase(Double.parseDouble(baseT.getText()));
        g.setTipoCalcolo(tipoArea);
        g.repaint();
        switch(tipoArea){
            case 0:
                break;
            case 1:
                risTxt.setText(""+g.calcolaCodaDestra());
                break;
            case 2:
                risTxt.setText(""+g.calcolaCodaSinistra());
                break;
            case 3:
                risTxt.setText(""+g.calcolaCode());
                break;
            case 4:
                risTxt.setText(""+g.calcolaAreaCompresa());
                break;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton areacRb;
    private javax.swing.JTextField baseT;
    private javax.swing.JPanel cGrafico;
    private javax.swing.JRadioButton codaDxRb;
    private javax.swing.JRadioButton codaSxRb;
    private javax.swing.JRadioButton codeRb;
    private javax.swing.JTextField dxT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea risTxt;
    private javax.swing.JTextField sxT;
    // End of variables declaration//GEN-END:variables
}
