/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calcoloradici;

import java.util.ArrayList;

/**
 *
 * @author Sebastiano
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    
    Grafico g;
    int grado=-1;
    int funz;
    int i;
    ArrayList<Double> vettPol;
    
    public Finestra() {
        initComponents();
        
        g=new Grafico(cGrafico.getWidth(), cGrafico.getHeight());
        cGrafico.add(g);
        vettPol=new ArrayList <Double>();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cGrafico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        bSin = new javax.swing.JRadioButton();
        pulisci = new javax.swing.JButton();
        calcRadici = new javax.swing.JButton();
        disegna = new javax.swing.JButton();
        dxExt = new javax.swing.JTextField();
        sxExt = new javax.swing.JTextField();
        bCos = new javax.swing.JRadioButton();
        bPol = new javax.swing.JRadioButton();
        labelPolinomio = new javax.swing.JLabel();
        polField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        polinomio = new javax.swing.JTextArea();
        conferma = new javax.swing.JButton();
        passo = new javax.swing.JTextField();
        approx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        cGrafico.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout cGraficoLayout = new javax.swing.GroupLayout(cGrafico);
        cGrafico.setLayout(cGraficoLayout);
        cGraficoLayout.setHorizontalGroup(
            cGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        cGraficoLayout.setVerticalGroup(
            cGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Estremo Destro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dominio");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Estremo SInistro");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Passo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Approssimazione");

        bSin.setBackground(new java.awt.Color(0, 0, 51));
        bSin.setForeground(new java.awt.Color(255, 255, 255));
        bSin.setSelected(true);
        bSin.setText("Sin(x)");
        bSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSinActionPerformed(evt);
            }
        });

        pulisci.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        pulisci.setText("Pulisci Grafico");
        pulisci.setEnabled(false);
        pulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulisciActionPerformed(evt);
            }
        });

        calcRadici.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calcRadici.setText("Calcola Radici");
        calcRadici.setEnabled(false);
        calcRadici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcRadiciActionPerformed(evt);
            }
        });

        disegna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        disegna.setText("Disegna");
        disegna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disegnaActionPerformed(evt);
            }
        });

        dxExt.setText("4");

        sxExt.setText("-4");

        bCos.setBackground(new java.awt.Color(0, 0, 51));
        bCos.setForeground(new java.awt.Color(255, 255, 255));
        bCos.setText("Cos(x)");
        bCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCosActionPerformed(evt);
            }
        });

        bPol.setBackground(new java.awt.Color(0, 0, 51));
        bPol.setForeground(new java.awt.Color(255, 255, 255));
        bPol.setText("Polinomio");
        bPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPolActionPerformed(evt);
            }
        });

        labelPolinomio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPolinomio.setForeground(new java.awt.Color(255, 255, 255));
        labelPolinomio.setText("Grado Polinomio");

        polField.setEnabled(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        polinomio.setBackground(new java.awt.Color(0, 51, 102));
        polinomio.setColumns(20);
        polinomio.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        polinomio.setForeground(new java.awt.Color(255, 255, 255));
        polinomio.setRows(5);
        polinomio.setEnabled(false);
        jScrollPane1.setViewportView(polinomio);

        conferma.setText("Conferma");
        conferma.setEnabled(false);
        conferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaActionPerformed(evt);
            }
        });

        passo.setText("0.01");

        approx.setText("0.0001");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(32, 32, 32))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dxExt)
                                            .addComponent(sxExt)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(approx))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(passo))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(cGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPol)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(polField)
                                    .addComponent(conferma, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1))
                            .addComponent(labelPolinomio))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(disegna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(calcRadici)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pulisci)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dxExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sxExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(passo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(approx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(disegna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulisci)
                            .addComponent(calcRadici)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(bSin)
                            .addGap(18, 18, 18)
                            .addComponent(bCos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelPolinomio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(polField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conferma)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disegnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disegnaActionPerformed
        g.setInit(false);
        g.setSx(Double.parseDouble(sxExt.getText()));
        g.setDx(Double.parseDouble(dxExt.getText()));
        g.setPasso(Double.parseDouble(passo.getText()));
        g.setApprox(Double.parseDouble(approx.getText()));
        g.repaint();
        g.passaPol(vettPol);
        pulisci.setEnabled(true);
        calcRadici.setEnabled(true);
    }//GEN-LAST:event_disegnaActionPerformed

    private void pulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulisciActionPerformed
        g.setInit(true);
        g.repaint();
        pulisci.setEnabled(false);
        calcRadici.setEnabled(false);
    }//GEN-LAST:event_pulisciActionPerformed

    private void confermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaActionPerformed
        try{
        if(conferma.getText()!=null&&Double.parseDouble(polField.getText())>=0){
            if(grado==-1){
                grado=(int)Double.parseDouble(polField.getText());
                i=(int)grado;
                labelPolinomio.setText("Coefficiente X^"+i);
            }
            else{
                
                if(i==0){
                    polinomio.append(""+Double.parseDouble(polField.getText()));
                    vettPol.add(Double.parseDouble(polField.getText()));
                    i--;
                }
                if(i>0){
                    vettPol.add(Double.parseDouble(polField.getText()));
                    polinomio.append(Double.parseDouble(polField.getText())+"x^"+i+" + ");
                    i--;
                    labelPolinomio.setText("Coefficiente X^"+i);
                    if(i==0){labelPolinomio.setText("Valore termine noto");}
                }
                if(i==-1){
                    conferma.setEnabled(false);
                    labelPolinomio.setText("Grado Polinomio");
                }
            }
        }
        }catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_confermaActionPerformed

    private void bSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSinActionPerformed
        bCos.setSelected(false);
        bPol.setSelected(false);
        g.setFunz(0);
        polField.setText("");
        labelPolinomio.setText("Grado Polinomio");
        polinomio.setText("");
        vettPol.clear();
        polField.setEnabled(false);
        conferma.setEnabled(false);
        grado=-1;
        vettPol.clear();
    }//GEN-LAST:event_bSinActionPerformed

    private void bPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPolActionPerformed
        bSin.setSelected(false);
        bCos.setSelected(false);
        g.setFunz(2);
        polField.setEnabled(true);
        conferma.setEnabled(true);
    }//GEN-LAST:event_bPolActionPerformed

    private void bCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCosActionPerformed
        bSin.setSelected(false);
        bPol.setSelected(false);
        g.setFunz(1);
        polField.setText("");
        labelPolinomio.setText("Grado Polinomio");
        polinomio.setText("");
        vettPol.clear();
        polField.setEnabled(false);
        conferma.setEnabled(false);
        grado=-1;
        vettPol.clear();
    }//GEN-LAST:event_bCosActionPerformed

    private void calcRadiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcRadiciActionPerformed
        g.setDisRadici(true);
        g.repaint();
    }//GEN-LAST:event_calcRadiciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField approx;
    private javax.swing.JRadioButton bCos;
    private javax.swing.JRadioButton bPol;
    private javax.swing.JRadioButton bSin;
    private javax.swing.JPanel cGrafico;
    private javax.swing.JButton calcRadici;
    private javax.swing.JButton conferma;
    private javax.swing.JButton disegna;
    private javax.swing.JTextField dxExt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelPolinomio;
    private javax.swing.JTextField passo;
    private javax.swing.JTextField polField;
    private javax.swing.JTextArea polinomio;
    private javax.swing.JButton pulisci;
    private javax.swing.JTextField sxExt;
    // End of variables declaration//GEN-END:variables
}
